In [2]:
## Numpy ndarray: 多维数组对象
import numpy as np
data = np.random.randn(2, 3)
data

array([[ 0.20988872,  0.56693946, -1.03222975],
       [-0.54987027, -0.03774751, -0.61598994]])

In [5]:
data * 10 

array([[ -1.9347145 ,  -7.48482588,   2.25512757],
       [ -5.69924738, -21.00496473,  -6.24538219]])

In [6]:
data + data

array([[-0.3869429 , -1.49696518,  0.45102551],
       [-1.13984948, -4.20099295, -1.24907644]])

In [12]:
n, m = data.shape

In [15]:
data.dtype

dtype('float64')

In [3]:
# 生成ndarray,应用array()
data1 = [6, 5, 4, 3, 2, 1]
arr1 = np.array(data1)
arr1

array([6, 5, 4, 3, 2, 1])

In [4]:
data2  = [[1, 2, 3, 4],[2, 3, 4, 5]]

In [6]:
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [8]:
# 检查数组属性
# ndim()
arr2.ndim

2

In [9]:
arr2.shape

(2, 4)

In [10]:
# 创建全为0，或者为1的数组
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [13]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
np.ones((3, 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [20]:
np.empty((2, 3, 2))

array([[[-2.68156159e+154,  1.73059623e-077],
        [ 8.89318163e-323,  0.00000000e+000],
        [ 0.00000000e+000,  0.00000000e+000]],

       [[ 0.00000000e+000,  0.00000000e+000],
        [ 0.00000000e+000,  0.00000000e+000],
        [ 0.00000000e+000,  0.00000000e+000]]])

In [21]:
# array将字符串为数字
numeric_strings = np.array(['1.23', '-9.1', '23'], dtype=np.string_)

In [23]:
numeric_strings.astype(float)

array([ 1.23, -9.1 , 23.  ])

In [24]:
# 基础索引和切片
arr = np.arange(10)

In [27]:
arr[0]

0

In [31]:
arr1 = arr[5:8].copy()

In [32]:
arr1

array([5, 6, 7])